[build]
  publish = "dist"
  command = "pnpm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# API redirects for cleaner URLs
[[redirects]]
  from = "/api/status"
  to = "/.netlify/functions/api-status"
  status = 200

[[redirects]]
  from = "/api/packages"
  to = "/.netlify/functions/api-packages"
  status = 200

[[redirects]]
  from = "/api/packages/install"
  to = "/.netlify/functions/api-package-install"
  status = 200

[[redirects]]
  from = "/api/reviews"
  to = "/.netlify/functions/api-reviews"
  status = 200

[[redirects]]
  from = "/api/execute"
  to = "/.netlify/functions/api-execute"
  status = 200

[[redirects]]
  from = "/api/stats"
  to = "/.netlify/functions/api-stats"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables (set these in Netlify dashboard)
# SUPABASE_URL = "https://your-project.supabase.co"
# SUPABASE_ANON_KEY = "your-anon-key"